#!/usr/bin/env node
/**
 * Single entry point to set the HTTPS host and regenerate manifests + event runtime.
 *
 *   node scripts/set-host.mjs
 *   node scripts/set-host.mjs https://files.example.com/quick-schedule-send
 *
 * The host is stored in host.config.json and substituted into both manifests.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const configPath = path.join(root, "host.config.json");

function normalizeHost(value) {
  if (!value || typeof value !== "string") {
    throw new Error("Host URL is required.");
  }
  let host = value.trim().replace(/\/+$/, "");
  if (!/^https:\/\//i.test(host)) {
    throw new Error("Host must be an https:// URL (Office add-ins require HTTPS).");
  }
  return host;
}

function readConfig() {
  const raw = JSON.parse(fs.readFileSync(configPath, "utf8"));
  return raw;
}

function writeConfig(host) {
  fs.writeFileSync(configPath, JSON.stringify({ host }, null, 2) + "\n");
}

function fill(template, host) {
  const url = new URL(host);
  return template
    .replaceAll("{{HOST}}", host)
    .replaceAll("{{HOST_NAME}}", url.host)
    .replaceAll("{{HOST_ORIGIN}}", url.origin);
}

function concatRuntime() {
  const parts = [
    fs.readFileSync(path.join(root, "src/lib/delay.js"), "utf8"),
    fs.readFileSync(path.join(root, "src/lib/office-schedule.js"), "utf8"),
    fs.readFileSync(path.join(root, "src/launchevent-handler.js"), "utf8")
  ];
  const banner =
    "/* Generated by scripts/set-host.mjs — do not edit. Source: src/lib/delay.js + src/lib/office-schedule.js + src/launchevent-handler.js */\n";
  fs.writeFileSync(path.join(root, "src/launchevent.js"), banner + parts.join("\n"));
}

function writeManifests(host) {
  const xmlTpl = fs.readFileSync(path.join(root, "templates/manifest.xml.tpl"), "utf8");
  const jsonTpl = fs.readFileSync(path.join(root, "templates/manifest.json.tpl"), "utf8");
  fs.writeFileSync(path.join(root, "manifest.xml"), fill(xmlTpl, host));
  fs.writeFileSync(path.join(root, "manifest.json"), fill(jsonTpl, host));
}

const arg = process.argv[2];
const config = readConfig();
const host = normalizeHost(arg || config.host);
if (arg) {
  writeConfig(host);
}
concatRuntime();
writeManifests(host);
console.log("Host: " + host);
console.log("Wrote manifest.xml, manifest.json, src/launchevent.js");
