/* Generated by scripts/set-host.mjs — do not edit. Source: src/lib/delay.js + src/lib/office-schedule.js + src/launchevent-handler.js */
/**
 * Delay maths for Quick Schedule Send.
 * Works as a script tag (global QuickSchedule) and as a Node module.
 * Keep this file import-free so it can be concatenated into launchevent.js.
 */
(function (root, factory) {
  var api = factory();
  if (typeof module === "object" && module.exports) {
    module.exports = api;
  }
  root.QuickSchedule = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  var DEFAULT_TIMEZONE = "Europe/London";
  var SESSION_KEY = "qsSchedule";
  var CUSTOM_PROP_KEY = "qsSchedule";
  var ROAMING_KEY = "qsPresets";
  var NOTIFICATION_KEY = "qsNotify";

  var DEFAULT_PRESETS = [
    { id: "ribbon-1h", label: "1h", kind: "offset", hours: 1, minutes: 0 },
    { id: "ribbon-2h", label: "2h", kind: "offset", hours: 2, minutes: 0 },
    { id: "ribbon-3h", label: "3h", kind: "offset", hours: 3, minutes: 0 },
    { id: "ribbon-4h", label: "4h", kind: "offset", hours: 4, minutes: 0 },
    {
      id: "ribbon-tomorrow",
      label: "Tomorrow 8am",
      kind: "tomorrow",
      hour: 8,
      minute: 0
    }
  ];

  var WINDOWS_TO_IANA = {
    "GMT Standard Time": "Europe/London",
    "Greenwich Standard Time": "Atlantic/Reykjavik",
    UTC: "UTC",
    "UTC Standard Time": "UTC"
  };

  function pad2(n) {
    return String(n).padStart(2, "0");
  }

  function isValidKind(kind) {
    return kind === "offset" || kind === "tomorrow";
  }

  function asInt(value, fallback) {
    var n = Number(value);
    if (!Number.isFinite(n)) {
      return fallback;
    }
    return Math.trunc(n);
  }

  function newId() {
    return "p-" + Date.now().toString(36) + "-" + Math.random().toString(36).slice(2, 8);
  }

  function normalizePreset(raw, index) {
    if (!raw || typeof raw !== "object") {
      return null;
    }
    var kind = raw.kind === "tomorrow" ? "tomorrow" : raw.kind === "offset" ? "offset" : null;
    if (!kind) {
      return null;
    }
    var label = String(raw.label || "").trim();
    if (!label) {
      label = kind === "tomorrow" ? "Tomorrow" : "+" + asInt(raw.hours, 0) + "h";
    }
    var preset = {
      id: String(raw.id || newId()),
      label: label.slice(0, 32),
      kind: kind
    };
    if (kind === "offset") {
      var hours = asInt(raw.hours, 0);
      var minutes = asInt(raw.minutes, 0);
      if (hours < 0 || minutes < 0 || (hours === 0 && minutes === 0)) {
        return null;
      }
      if (minutes >= 60) {
        hours += Math.floor(minutes / 60);
        minutes = minutes % 60;
      }
      if (hours > 24 * 14) {
        return null;
      }
      preset.hours = hours;
      preset.minutes = minutes;
    } else {
      var hour = asInt(raw.hour, 8);
      var minute = asInt(raw.minute, 0);
      if (hour < 0 || hour > 23 || minute < 0 || minute > 59) {
        return null;
      }
      preset.hour = hour;
      preset.minute = minute;
    }
    if (typeof index === "number") {
      preset.slot = index;
    }
    return preset;
  }

  function normalizePresets(list) {
    if (!Array.isArray(list)) {
      return DEFAULT_PRESETS.map(function (p) {
        return normalizePreset(p);
      });
    }
    var out = [];
    for (var i = 0; i < list.length; i++) {
      var preset = normalizePreset(list[i], i);
      if (preset) {
        out.push(preset);
      }
    }
    return out;
  }

  function zonedParts(date, timeZone) {
    var fmt = new Intl.DateTimeFormat("en-GB", {
      timeZone: timeZone,
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      hourCycle: "h23"
    });
    var map = {};
    fmt.formatToParts(date).forEach(function (part) {
      if (part.type !== "literal") {
        map[part.type] = part.value;
      }
    });
    return {
      year: Number(map.year),
      month: Number(map.month),
      day: Number(map.day),
      hour: Number(map.hour),
      minute: Number(map.minute),
      second: Number(map.second)
    };
  }

  function getOffsetMs(instant, timeZone) {
    var parts = zonedParts(new Date(instant), timeZone);
    var asUtc = Date.UTC(
      parts.year,
      parts.month - 1,
      parts.day,
      parts.hour,
      parts.minute,
      parts.second
    );
    return asUtc - instant;
  }

  /**
   * Convert a civil wall time in `timeZone` to a Date (UTC instant).
   * Iterates once so DST spring-forward / fall-back is resolved.
   */
  function zonedLocalToDate(year, month, day, hour, minute, timeZone) {
    var utcGuess = Date.UTC(year, month - 1, day, hour, minute, 0);
    var instant = utcGuess - getOffsetMs(utcGuess, timeZone);
    instant = utcGuess - getOffsetMs(instant, timeZone);
    var check = zonedParts(new Date(instant), timeZone);
    if (
      check.year !== year ||
      check.month !== month ||
      check.day !== day ||
      check.hour !== hour ||
      check.minute !== minute
    ) {
      instant += Date.UTC(year, month - 1, day, hour, minute, 0) -
        Date.UTC(check.year, check.month - 1, check.day, check.hour, check.minute, 0);
    }
    return new Date(instant);
  }

  function addCalendarDays(parts, days) {
    var utc = Date.UTC(parts.year, parts.month - 1, parts.day + days);
    var d = new Date(utc);
    return {
      year: d.getUTCFullYear(),
      month: d.getUTCMonth() + 1,
      day: d.getUTCDate()
    };
  }

  function addOffset(now, hours, minutes) {
    var ms = (asInt(hours, 0) * 60 + asInt(minutes, 0)) * 60 * 1000;
    if (ms <= 0) {
      throw new Error("Offset must be greater than zero.");
    }
    return new Date(now.getTime() + ms);
  }

  function tomorrowAt(now, hour, minute, timeZone) {
    var tz = timeZone || DEFAULT_TIMEZONE;
    var today = zonedParts(now, tz);
    var next = addCalendarDays(today, 1);
    return zonedLocalToDate(next.year, next.month, next.day, hour, minute, tz);
  }

  function applyPresetToDate(preset, now, timeZone) {
    var clean = normalizePreset(preset);
    if (!clean) {
      throw new Error("Invalid schedule preset.");
    }
    var when = now instanceof Date ? now : new Date(now);
    if (Number.isNaN(when.getTime())) {
      throw new Error("Invalid start time.");
    }
    if (clean.kind === "offset") {
      return addOffset(when, clean.hours, clean.minutes);
    }
    return tomorrowAt(when, clean.hour, clean.minute, timeZone || DEFAULT_TIMEZONE);
  }

  function humanOffset(hours, minutes) {
    var h = asInt(hours, 0);
    var m = asInt(minutes, 0);
    var parts = [];
    if (h > 0) {
      parts.push(h === 1 ? "1 hour" : h + " hours");
    }
    if (m > 0) {
      parts.push(m === 1 ? "1 minute" : m + " minutes");
    }
    return parts.join(" ");
  }

  var NOTIFY_MAX = 150;
  var DRAFT_HINT = "To change after sending: open it from Drafts.";
  var CLEARED_MESSAGE = "Schedule cleared, will send immediately";

  function formatLocalHm(date) {
    return pad2(date.getHours()) + ":" + pad2(date.getMinutes());
  }

  function formatLocalTomorrow(now) {
    var d = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1);
    var weekday = d.toLocaleDateString("en-GB", { weekday: "short" });
    var month = d.toLocaleDateString("en-GB", { month: "short" });
    return weekday + " " + d.getDate() + " " + month;
  }

  function packNotification(line1, line2) {
    var options = [
      line1 + "\n" + line2,
      line1 + " " + line2,
      line1 + "\nChange later: open from Drafts.",
      line1 + " Change later: open from Drafts.",
      line1
    ];
    for (var i = 0; i < options.length; i++) {
      if (options[i].length <= NOTIFY_MAX) {
        return options[i];
      }
    }
    return line1.slice(0, NOTIFY_MAX);
  }

  function describeScheduledBar(preset, now) {
    var clean = normalizePreset(preset);
    if (!clean) {
      return {
        message: "No send delay selected.",
        line1: "No send delay selected.",
        summary: "None",
        persistent: false
      };
    }
    var when = now instanceof Date ? now : new Date(now || Date.now());
    var line1;
    var summary;
    if (clean.kind === "offset") {
      var human = humanOffset(clean.hours, clean.minutes);
      var about = formatLocalHm(addOffset(when, clean.hours, clean.minutes));
      line1 =
        "Scheduled: sends " +
        human +
        " after you press Send (about " +
        about +
        " if you send now)";
      summary = human + " after Send";
    } else {
      var clock = pad2(clean.hour) + ":" + pad2(clean.minute);
      line1 =
        "Scheduled: sends tomorrow (" +
        formatLocalTomorrow(when) +
        ") at " +
        clock;
      summary = "Tomorrow " + clock + " after Send";
    }
    return {
      message: packNotification(line1, DRAFT_HINT),
      line1: line1,
      summary: summary,
      persistent: true
    };
  }

  function describeSchedule(preset, now) {
    return describeScheduledBar(preset, now);
  }

  function resolveTimeZone(officeTimeZone) {
    try {
      var iana = Intl.DateTimeFormat().resolvedOptions().timeZone;
      if (iana) {
        return iana;
      }
    } catch (e) {
      /* ignore */
    }
    if (officeTimeZone && WINDOWS_TO_IANA[officeTimeZone]) {
      return WINDOWS_TO_IANA[officeTimeZone];
    }
    return DEFAULT_TIMEZONE;
  }

  function itemFingerprint(item) {
    if (!item || typeof item !== "object") {
      return { itemId: "", conversationId: "" };
    }
    return {
      itemId: String(item.itemId || ""),
      conversationId: String(item.conversationId || "")
    };
  }

  function isComposeSurface(item) {
    if (!item || typeof item !== "object") {
      return false;
    }
    if (item.surface === "read") {
      return false;
    }
    if (item.surface === "compose") {
      return true;
    }
    return item.sessionData != null || item._compose === true;
  }

  function fingerprintsMatch(intended, current) {
    var a = itemFingerprint(intended);
    var b = itemFingerprint(current);
    if (a.itemId && b.itemId) {
      return a.itemId === b.itemId;
    }
    return true;
  }

  function serializeSchedule(preset, meta) {
    var clean = normalizePreset(preset);
    if (!clean) {
      return "";
    }
    meta = meta || {};
    return JSON.stringify({
      v: 2,
      preset: clean,
      chosenAt: meta.chosenAt || Date.now(),
      nonce: meta.nonce || newId(),
      itemId: meta.itemId || "",
      conversationId: meta.conversationId || ""
    });
  }

  function parseStoredSchedule(raw) {
    if (!raw) {
      return null;
    }
    try {
      var data = typeof raw === "string" ? JSON.parse(raw) : raw;
      if (!data || data.cleared) {
        return null;
      }
      var preset = normalizePreset(data.preset || (data.kind ? data : null));
      if (!preset) {
        return null;
      }
      return {
        v: Number(data.v) || 1,
        preset: preset,
        chosenAt: Number(data.chosenAt) || 0,
        nonce: String(data.nonce || ""),
        itemId: String(data.itemId || ""),
        conversationId: String(data.conversationId || "")
      };
    } catch (e) {
      return null;
    }
  }

  function scheduleAppliesToItem(stored, currentItem) {
    if (!stored || !stored.preset) {
      return null;
    }
    if (!isComposeSurface(currentItem)) {
      return null;
    }
    var fp = itemFingerprint(currentItem);
    if (stored.itemId && fp.itemId && stored.itemId !== fp.itemId) {
      return null;
    }
    return stored.preset;
  }

  function parseSchedule(raw, currentItem) {
    var stored = parseStoredSchedule(raw);
    if (!stored) {
      return null;
    }
    if (currentItem) {
      return scheduleAppliesToItem(stored, currentItem);
    }
    return stored.preset;
  }

  /**
   * Single write policy. Select/read/itemChanged must never write.
   * customProperties are ignored even if a parent message left them behind.
   */
  function planWrites(event) {
    var empty = {
      writes: [],
      allowEvent: true,
      applyDelay: false,
      preset: null
    };
    if (!event || typeof event !== "object") {
      return empty;
    }
    var type = event.type;
    if (type === "select" || type === "read" || type === "itemChanged") {
      return empty;
    }
    var item = event.item;
    if (type === "send") {
      if (!isComposeSurface(item)) {
        return empty;
      }
      var preset = scheduleAppliesToItem(parseStoredSchedule(event.sessionData), item);
      if (!preset) {
        return empty;
      }
      return {
        writes: ["delayDeliveryTime.set", "sessionData.remove"],
        allowEvent: true,
        applyDelay: true,
        preset: preset
      };
    }
    if (type === "composeClick") {
      if (!isComposeSurface(item)) {
        return empty;
      }
      if (event.action === "clear") {
        return {
          writes: ["sessionData.remove", "notification"],
          allowEvent: true,
          applyDelay: false,
          preset: null
        };
      }
      var chosen = normalizePreset(event.preset);
      if (!chosen) {
        return empty;
      }
      return {
        writes: ["sessionData.set", "notification"],
        allowEvent: true,
        applyDelay: false,
        preset: chosen
      };
    }
    return empty;
  }

  return {
    DEFAULT_TIMEZONE: DEFAULT_TIMEZONE,
    DEFAULT_PRESETS: DEFAULT_PRESETS,
    SESSION_KEY: SESSION_KEY,
    CUSTOM_PROP_KEY: CUSTOM_PROP_KEY,
    ROAMING_KEY: ROAMING_KEY,
    NOTIFICATION_KEY: NOTIFICATION_KEY,
    isValidKind: isValidKind,
    newId: newId,
    normalizePreset: normalizePreset,
    normalizePresets: normalizePresets,
    zonedParts: zonedParts,
    zonedLocalToDate: zonedLocalToDate,
    addCalendarDays: addCalendarDays,
    addOffset: addOffset,
    tomorrowAt: tomorrowAt,
    applyPresetToDate: applyPresetToDate,
    describeSchedule: describeSchedule,
    describeScheduledBar: describeScheduledBar,
    packNotification: packNotification,
    formatLocalHm: formatLocalHm,
    formatLocalTomorrow: formatLocalTomorrow,
    NOTIFY_MAX: NOTIFY_MAX,
    DRAFT_HINT: DRAFT_HINT,
    CLEARED_MESSAGE: CLEARED_MESSAGE,
    humanOffset: humanOffset,
    resolveTimeZone: resolveTimeZone,
    serializeSchedule: serializeSchedule,
    parseStoredSchedule: parseStoredSchedule,
    parseSchedule: parseSchedule,
    scheduleAppliesToItem: scheduleAppliesToItem,
    itemFingerprint: itemFingerprint,
    isComposeSurface: isComposeSurface,
    fingerprintsMatch: fingerprintsMatch,
    planWrites: planWrites,
    pad2: pad2
  };
});

/**
 * Office.js helpers for choosing a delay and applying it on Send.
 * Concatenated into launchevent.js after delay.js. Uses global QuickSchedule.
 *
 * Writes are allowed only after an explicit compose button click, or in
 * OnMessageSend for that same compose item. Select/read must never write.
 */
(function (root) {
  "use strict";

  var QS = root.QuickSchedule;
  if (!QS) {
    throw new Error("QuickSchedule delay library must load first.");
  }

  var NOTIFY_ICON = "Icon.16x16";
  var CLEARED_MESSAGE = QS.CLEARED_MESSAGE;

  function later(fn, ms) {
    var t = typeof setTimeout === "function" ? setTimeout : null;
    if (t) {
      t(fn, ms);
    } else {
      fn();
    }
  }

  function mailboxSet(version) {
    try {
      return !!(
        Office &&
        Office.context &&
        Office.context.requirements &&
        Office.context.requirements.isSetSupported("Mailbox", version)
      );
    } catch (e) {
      return false;
    }
  }

  function officeTimeZone() {
    try {
      return QS.resolveTimeZone(Office.context.mailbox.userProfile.timeZone);
    } catch (e) {
      return QS.resolveTimeZone();
    }
  }

  function currentItem() {
    try {
      return Office.context && Office.context.mailbox && Office.context.mailbox.item;
    } catch (e) {
      return null;
    }
  }

  function isComposeItem(item) {
    if (!item) {
      return false;
    }
    if (!item.sessionData) {
      return false;
    }
    return true;
  }

  function withComposeItem(cb, onMissing) {
    var item = currentItem();
    if (!isComposeItem(item)) {
      if (onMissing) {
        onMissing(new Error("Not a compose item."));
      }
      return;
    }
    cb(item);
  }

  function once(fn) {
    var called = false;
    return function () {
      if (called) {
        return;
      }
      called = true;
      if (fn) {
        fn.apply(null, arguments);
      }
    };
  }

  function stillIntended(intended) {
    var item = currentItem();
    return isComposeItem(item) && QS.fingerprintsMatch(intended, item);
  }

  function canUseSessionData(item) {
    return (
      mailboxSet("1.11") &&
      isComposeItem(item) &&
      typeof item.sessionData.getAsync === "function" &&
      typeof item.sessionData.setAsync === "function"
    );
  }

  function canNotify(item) {
    return mailboxSet("1.3") && item && item.notificationMessages;
  }

  function readSchedule(callback) {
    var done = once(callback);
    withComposeItem(
      function (item) {
        if (!canUseSessionData(item)) {
          done(null);
          return;
        }
        item.sessionData.getAsync(QS.SESSION_KEY, function (result) {
          if (!result || result.status === Office.AsyncResultStatus.Failed) {
            done(null);
            return;
          }
          done(QS.parseSchedule(result.value, item));
        });
      },
      function () {
        done(null);
      }
    );
  }

  function writeSession(item, payload, done) {
    if (!canUseSessionData(item)) {
      done();
      return;
    }
    try {
      if (payload) {
        item.sessionData.setAsync(QS.SESSION_KEY, payload, function () {
          done();
        });
      } else if (typeof item.sessionData.removeAsync === "function") {
        item.sessionData.removeAsync(QS.SESSION_KEY, function () {
          done();
        });
      } else {
        item.sessionData.setAsync(QS.SESSION_KEY, "", function () {
          done();
        });
      }
    } catch (e) {
      done();
    }
  }

  function replaceInfoNotification(item, message, persistent, done) {
    if (!canNotify(item)) {
      if (done) {
        done();
      }
      return;
    }
    try {
      item.notificationMessages.replaceAsync(
        QS.NOTIFICATION_KEY,
        {
          type: Office.MailboxEnums.ItemNotificationMessageType.InformationalMessage,
          message: String(message).slice(0, QS.NOTIFY_MAX),
          icon: NOTIFY_ICON,
          persistent: persistent !== false
        },
        function () {
          if (done) {
            done();
          }
        }
      );
    } catch (e) {
      if (done) {
        done();
      }
    }
  }

  function writeSchedule(preset, callback) {
    var done = once(callback);
    later(done, 2500);
    withComposeItem(
      function (item) {
        var plan = QS.planWrites({
          type: "composeClick",
          action: preset ? "choose" : "clear",
          item: { surface: "compose", itemId: item.itemId, conversationId: item.conversationId, sessionData: true },
          preset: preset
        });
        if (!plan.writes.length) {
          done();
          return;
        }
        var intended = QS.itemFingerprint(item);
        var payload = preset
          ? QS.serializeSchedule(preset, {
              itemId: intended.itemId,
              conversationId: intended.conversationId
            })
          : "";
        writeSession(item, payload, function () {
          if (!stillIntended(intended)) {
            done();
            return;
          }
          var live = currentItem();
          if (preset) {
            replaceInfoNotification(live, QS.describeScheduledBar(preset, new Date()).message, true, done);
          } else {
            replaceInfoNotification(live, QS.CLEARED_MESSAGE, false, done);
          }
        });
      },
      function () {
        done();
      }
    );
  }

  function showChosenNotification(preset, callback) {
    var done = once(callback);
    later(done, 2500);
    withComposeItem(
      function (item) {
        replaceInfoNotification(item, QS.describeScheduledBar(preset, new Date()).message, true, done);
      },
      function () {
        done();
      }
    );
  }

  function showClearedNotification(callback) {
    var done = once(callback);
    later(done, 2500);
    withComposeItem(
      function (item) {
        replaceInfoNotification(item, CLEARED_MESSAGE, false, done);
      },
      function () {
        done();
      }
    );
  }

  function readRoamingPresets() {
    try {
      if (!Office.context || !Office.context.roamingSettings) {
        return QS.normalizePresets(QS.DEFAULT_PRESETS);
      }
      var raw = Office.context.roamingSettings.get(QS.ROAMING_KEY);
      if (!raw) {
        return QS.normalizePresets(QS.DEFAULT_PRESETS);
      }
      var parsed = typeof raw === "string" ? JSON.parse(raw) : raw;
      var list = QS.normalizePresets(parsed);
      return list.length ? list : QS.normalizePresets(QS.DEFAULT_PRESETS);
    } catch (e) {
      return QS.normalizePresets(QS.DEFAULT_PRESETS);
    }
  }

  function saveRoamingPresets(presets, callback) {
    var list = QS.normalizePresets(presets);
    try {
      Office.context.roamingSettings.set(QS.ROAMING_KEY, JSON.stringify(list));
      Office.context.roamingSettings.saveAsync(function (result) {
        if (callback) {
          callback(result);
        }
      });
    } catch (e) {
      if (callback) {
        callback({ status: "failed", error: e });
      }
    }
  }

  function choosePreset(preset, onDone) {
    var clean = QS.normalizePreset(preset);
    if (!clean) {
      if (onDone) {
        onDone(new Error("Invalid preset."));
      }
      return;
    }
    writeSchedule(clean, function () {
      if (onDone) {
        onDone(null, clean);
      }
    });
  }

  function clearSchedule(onDone) {
    writeSchedule(null, function () {
      if (onDone) {
        onDone();
      }
    });
  }

  function completeCommand(event) {
    if (!event || event.__qsCompleted) {
      return;
    }
    event.__qsCompleted = true;
    try {
      event.completed();
    } catch (e) {
      /* already completed */
    }
  }

  function completeSend(event, options) {
    if (!event || event.__qsCompleted) {
      return;
    }
    event.__qsCompleted = true;
    try {
      event.completed(options || { allowEvent: true });
    } catch (e) {
      try {
        event.completed({ allowEvent: true });
      } catch (e2) {
        /* already completed */
      }
    }
  }

  function applyDelayOnSend(event) {
    var finish = function (options) {
      completeSend(event, options || { allowEvent: true });
    };
    later(function () {
      finish({ allowEvent: true });
    }, 5000);
    try {
      var item = currentItem();
      if (!isComposeItem(item) || !canUseSessionData(item)) {
        finish({ allowEvent: true });
        return;
      }
      item.sessionData.getAsync(QS.SESSION_KEY, function (result) {
        var raw = result && result.status !== Office.AsyncResultStatus.Failed ? result.value : "";
        var live = currentItem();
        var plan = QS.planWrites({
          type: "send",
          item: {
            surface: "compose",
            itemId: live && live.itemId,
            conversationId: live && live.conversationId,
            sessionData: true
          },
          sessionData: raw,
          customProperties: null
        });
        if (!plan.applyDelay) {
          finish({ allowEvent: true });
          return;
        }
        if (!stillIntended(live)) {
          finish({ allowEvent: true });
          return;
        }
        var when;
        try {
          when = QS.applyPresetToDate(plan.preset, new Date(), officeTimeZone());
        } catch (e) {
          finish({ allowEvent: true });
          return;
        }
        if (!mailboxSet("1.13") || !live.delayDeliveryTime || !live.delayDeliveryTime.setAsync) {
          finish({ allowEvent: true });
          return;
        }
        live.delayDeliveryTime.setAsync(when, function () {
          var after = currentItem();
          if (isComposeItem(after) && canUseSessionData(after) && QS.fingerprintsMatch(live, after)) {
            writeSession(after, "", function () {
              finish({ allowEvent: true });
            });
            return;
          }
          finish({ allowEvent: true });
        });
      });
    } catch (e) {
      finish({ allowEvent: true });
    }
  }

  function applyRibbonSlot(slotIndex, event) {
    var finish = function () {
      completeCommand(event);
    };
    later(finish, 4000);
    try {
      if (!isComposeItem(currentItem())) {
        finish();
        return;
      }
      var presets = readRoamingPresets();
      var preset = presets[slotIndex] || QS.DEFAULT_PRESETS[slotIndex];
      choosePreset(preset, function () {
        finish();
      });
    } catch (e) {
      finish();
    }
  }

  function applyClearSchedule(event) {
    var finish = function () {
      completeCommand(event);
    };
    later(finish, 4000);
    try {
      if (!isComposeItem(currentItem())) {
        finish();
        return;
      }
      clearSchedule(function () {
        finish();
      });
    } catch (e) {
      finish();
    }
  }

  root.QuickScheduleOffice = {
    officeTimeZone: officeTimeZone,
    readSchedule: readSchedule,
    writeSchedule: writeSchedule,
    choosePreset: choosePreset,
    clearSchedule: clearSchedule,
    showChosenNotification: showChosenNotification,
    showClearedNotification: showClearedNotification,
    readRoamingPresets: readRoamingPresets,
    saveRoamingPresets: saveRoamingPresets,
    applyDelayOnSend: applyDelayOnSend,
    applyRibbonSlot: applyRibbonSlot,
    applyClearSchedule: applyClearSchedule
  };
})(typeof globalThis !== "undefined" ? globalThis : this);

/* global Office, QuickScheduleOffice */

function onMessageSendHandler(event) {
  try {
    QuickScheduleOffice.applyDelayOnSend(event);
  } catch (e) {
    if (event && !event.__qsCompleted) {
      try {
        event.completed({ allowEvent: true });
      } catch (e2) {
        /* ignore */
      }
    }
  }
}

function registerLaunchActions() {
  if (typeof Office === "undefined" || !Office.actions || !Office.actions.associate) {
    return false;
  }
  Office.actions.associate("onMessageSendHandler", onMessageSendHandler);
  return true;
}

registerLaunchActions();
if (typeof Office !== "undefined" && Office.onReady) {
  Office.onReady(function () {
    registerLaunchActions();
  });
}

if (typeof globalThis !== "undefined") {
  globalThis.onMessageSendHandler = onMessageSendHandler;
}
